name: Run Tests

on:
  push:
    branches:
      - main
      - alice/firebaseTesting
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Node.js environment
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: npm install

    # Step 4: Install Firebase CLI
    - name: Install Firebase CLI
      run: npm install -g firebase-tools

    # Step 5: Set up Firestore emulator and run tests
    - name: Start Firebase Emulator
      run: |
        firebase emulators:start --only firestore &
        sleep 10 # Give emulator some time to start

    - name: Run tests
      run: npm test -- --detectOpenHandles
      working-directory: sincerely

    # Optional: Cache node modules
    - name: Cache node modules
      uses: actions/cache@v3
      with:
        path: node_modules
        key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-modules-
