name: Run Tests

on:
  push:
    branches:
      - main
      - alice/firebaseTesting
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Node.js environment
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22'  # Make sure this is the correct version for your project

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        cd sincerely  # Change directory to the `sincerely` folder where package.json is
        npm install

    # Step 4: Run tests
    - name: Run tests
      run: |
        cd sincerely  # Ensure we're in the correct directory to run tests
        npm test -- --detectOpenHandles  # Add any additional flags or commands if needed

    # Optional: Cache dependencies to speed up the workflow
    - name: Cache node modules
      uses: actions/cache@v3
      with:
        path: sincerely/node_modules  # Specify the correct path to node_modules
        key: ${{ runner.os }}-node-modules-${{ hashFiles('**/sincerely/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-modules-
